### ISSUE TITLE
Please do not release nothing that DON'T WORK and pay me your faults rotten dork.

### ISSUE THREAD

**Issue by budlol** [spudgy/UnrealEngine4-SwissKnife#1]
Source is 100% bugged. BILLION+BILLION+BILLION of **WANTED ERRORS**
Sucker, faker, lamers, clones and cloners MUST DIRE FOR EVER TO EVER.
9999999999 hours spents for help.. Result.... NO WORK NO HOME NO FAMILY NO LIVE.
Sent messages of help request. "NO ONE REPLY".
Please im a real poor FUCKING DYING GOD:::: so if you have full working source, good.. If not DIE TODAY PLEASE!

https://freeimage.host/i/muorimerda.JIGzKl

**Comment by spudgy** [comment]
I should have seen this comming lol
